# Generated by Django 5.1.4 on 2025-01-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='food_price',
        ),
    ]
