# Generated by Django 5.1.4 on 2025-01-27 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_price_cart_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='time_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_time', to='api.food'),
        ),
    ]
