# Generated by Django 5.1.4 on 2025-01-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
